spring.application.name=demo
server.port=8081
spring.main.allow-circular-references=true

# MongoDB??
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=duser
spring.data.mongodb.auto-index-creation=true

# ????
logging.level.root=INFO
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.bcu=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# AI??
spring.ai.model.chat=zhipuai
spring.ai.zhipuai.api-key=fcf7d1e50ed24ee6af3a2be4df927752.xPjirfPxG4vzDw5p
spring.ai.zhipuai.chat.options.model=glm-4-air
spring.ai.zhipuai.chat.options.temperature=0.7

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=D:/zong/STInternshipManagerProject-dev/uploads
spring.servlet.multipart.enabled=true

# 文件上传配置
file.upload.signature-dir=D:/zong/STInternshipManagerProject-dev/uploads/signatures

