spring.application.name=demo
server.port=8081
spring.main.allow-circular-references=true

# MongoDB??
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=duser
spring.data.mongodb.auto-index-creation=true

# ????
logging.level.root=INFO
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.bcu=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# AI??
spring.ai.model.chat=zhipuai
spring.ai.zhipuai.api-key=d10502cb2dce408fabb85b8377a20a2f.QidPjXoG3JAud4Xz
spring.ai.zhipuai.chat.options.model=glm-4-air
spring.ai.zhipuai.chat.options.temperature=0.7

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=D:/scores
spring.servlet.multipart.enabled=true

# æä»¶ä¸ä¼ éç½®
file.upload.signature-dir=D:/signatures

