name: Spring Boot Build Check

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Extract Java version from pom.xml
        id: extract-java
        run: |
          cd backend
          JAVA_VERSION=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "//x:project/x:properties/x:java.version" pom.xml)
          if [ -z "$JAVA_VERSION" ]; then
            echo "❌ Error: <java.version> not found in pom.xml"
            exit 1
          fi
          echo "✅ Detected Java version: $JAVA_VERSION"
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.extract-java.outputs.java-version }}
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests
      - name: Upload release version
        uses: actions/upload-artifact@v4
        with:
          name: backend.zip
          compression-level: 9
          path: backend/target/backend.jar
